#!/usr/bin/env bash

./node_modules/pre-commit/hook

RESULT=$?

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
STAGED_STYLE_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".scss$")

STYLE_LINT=stylelint
ES_LINT=eslint


PASS=true

echo "Checking for Linting Errors..........."

# Function to check for linting
linting() {
  if [[ "$1" == "" ]]; then
    echo "No $3 related files have been changed"
    return 0
  fi
  which "$2"  &> /dev/null
  if [[ "$?" == 1 ]]; then
    echo "Please install $2 globally; run: npm install $2 javascript"
    exit 1
  fi
  echo "Validating $3 ..........."
  for FILE in "$1"
  do
    "$2" $FILE
    if [[ "$?" == 0 ]]; then
      echo "$2 Passed: $FILE"
    else
      PASS=false
    fi
  done
}

linting "$STAGED_FILES" "$ES_LINT" "javascript"
linting "$STAGED_STYLE_FILES" "$STYLE_LINT" "SCSS"

if ! $PASS; then
  echo "COMMIT FAILED: Your commit contains files that should pass ESLint or StyleLint but do not. Please fix the Linting errors and try again."
  exit 1
fi

[ $RESULT -ne 0 ] && exit 1

exit 0

