export const IS_LOADING = 'IS_LOADING';
export const LOAD_ACTIVE_USER_SUCCESS = 'LOAD_ACTIVE_USER_SUCCESS';
export const SET_MENUS = 'SET_MENUS';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const FETCH_ORDERS_LOADING = 'FETCH_ORDERS_LOADING';
export const FETCH_FILTERED_ORDERS = 'FETCH_FILTERED_ORDERS';
